#!/bin/sh

# @thanks https://frankcorso.dev/automatically-run-build-scripts-switching-branches-git-hooks.html
# Args passed to this are:
# $1 - Previous HEAD
# $2 - New HEAD
# $3 - 1 if checking out a branch, 0 if checking out something else, such as a file (rollbacks)

STATUS=0

if [ "$1" != "$2" ]; then
    echo "post-checkout: $1 $2 $3"
fi

if [ "1" != "$3" ]; then
    exit $STATUS
fi

if [ "$1" = "$2" ]; then
    exit $STATUS
fi

if [ -f "composer.lock" ] && [ "$(git show "$1:composer.lock" | sha256sum)" != "$(git show "$2:composer.lock" | sha256sum)" ]; then
    printf "\e[32mSyncing\e[0m composer dependencies\n"

    phpx "$(which composer)" install  --no-interaction --no-progress --ignore-platform-req=ext-gd 2>&-

    STATUS=$?
elif [ -f "composer.json" ] && [ "$(git show "$1:composer.json" | sha256sum)" != "$(git show "$2:composer.json" | sha256sum)" ]; then
    printf "\e[34mInstalling\e[0m composer dependencies\n"

    # @thanks https://stackoverflow.com/a/2342841/15601185
    # 2>&1          : Send stderr to stdout
    # 1> /dev/null  : Send stdout to black hole
    # phpx `which composer` install  --no-interaction --no-progress --ignore-platform-req=ext-gd 2>&1 1> /dev/null
    phpx "$(which composer)" install  --no-interaction --no-progress --ignore-platform-req=ext-gd 2>&-

    STATUS=$?
fi


if [ $STATUS != 0 ]; then
    exit $STATUS
fi

if [ -f "package-lock.json" ] && [ "$(git show "$1:package-lock.json" | sha256sum)" != "$(git show "$2:package-lock.json" | sha256sum)" ]; then
    printf "\e[32mSyncing\e[0m npm dependencies\n"

    npm ci > /dev/null 2>&1

    STATUS=$?
elif [ -f "package.json" ] && [ "$(git show "$1:package.json" | sha256sum)" != "$(git show "$2:package.json" | sha256sum)" ]; then
    printf "\e[34mInstalling\e[0m npm dependencies\n"

    npm install > /dev/null 2>&1

    STATUS=$?
fi

exit $STATUS
