# Dynamic Docker Run (based in current path):
#   - drun db bash
drun() {
    docker exec -w `pwd` -it "$@"

    return $?
}

# OpenSSL PEM:
#   - osp duckduck.com:443
osp() {
    openssl s_client -connect "$@" -showcerts </dev/null | openssl x509 -outform pem > "$@".pem

    return $?
}

# OpenSSL Body:
#   - osb duckduck.com:443.pem
osb() {
    sed '1d;/^\s.*/d' "$@" > body.txt
    STATUS="$?"

    if [ $STATUS -ne 0 ]; then
        rm -f body.txt

        return $STATUS
    fi

    cat body.txt | yy | rm body.txt

    return $?
}

# OpenSSL Private Key:
#   - osi duckduck.com:443.pem
osi() {
    openssl pkey -in "$@" -out pkey.txt
    STATUS="$?"

    if [ $STATUS -ne 0 ]; then
        rm -f pkey.txt

        return $STATUS
    fi

    cat pkey.txt | yy | rm pkey.txt

    return $?
}


# PHP Syntax Check:
#   - pcs
#   - pcs 7.4
pcs() {
    phplint $(command ls -1 -d */ | grepx -v 'vendor|node_modules|.git' | xargs -I {} echo -n ' {}') "$@"

    return $?
}

# Change Dir Project
#   - cdp /var/www/html/flexphp
cdp() {
    cd "$@"/$(cd "$@" && command ls -L1 | fzf) && $EDITOR

    return $?
}

# Change Terminal Theme
#   - ctm Light
ctt() {
    sed -i "s/ColorScheme=.*/ColorScheme=${1}/g" /var/www/html/freddiegar/services/emulator/konsole/konsole.profile

    konsoleprofile colors=$1

    if [ "$1" = "Dark" ] ; then
        export BAT_THEME='gruvbox-dark'
        sed -i 's/BAT_THEME="gruvbox-light"/BAT_THEME="gruvbox-dark"/g' ~/.profile
    else
        export BAT_THEME="gruvbox-light"
        sed -i 's/BAT_THEME="gruvbox-dark"/BAT_THEME="gruvbox-light"/g' ~/.profile
    fi
}

alias \?="apropos"
alias x="exit"
alias v=$EDITOR
alias e=$EDITOR
alias g="grepx"
alias n="neovide"
alias m="man"
alias l="less"
alias t="sh testx.sh"
alias h="history"
alias d="diff"
alias f="fzf"
alias a="alias"
alias w="which"
alias o="xargs -t -r -I {}"
alias s="bash ~/working/mysqlog.sh"
alias r="bash ~/working/mysqlget.sh"
alias q="bash ~/working/evertec/queues.sh"
alias p="ps -fea -U \$USER -u \$USER --forest"

# @thanks https://rafaelc.org/posts/copying-previous-commands-with-fzf-and-zsh/
alias hh="fc -ln 0 | awk '!a[\$0]++' | fzf --tac | tr -d \"\n\" | xclip -selection clipboard"
alias di="diff -rq --suppress-common-lines"
alias ll="command ls -lh"
alias lg="exa --git"
alias le="find . -size 0 | grepx -v 'ignore|node_modules|vendor|storage|coverage|.git/'"
alias lsd="command ls -la | grep '^d'"
alias lsn="command ls -L1"
alias __="ssh-add"
alias rga="rg --no-ignore --hidden --glob '!{.git,*.log,*-lock.json,*.lock,var/*,storage/*,node_modules/*,*/var/*,*/storage/*,*/node_modules/*}'"
alias npkg="dpkg --list | wc --lines"

alias kd="ctt Dark"
alias kl="ctt Light"

alias vf="vifm"
alias vd="$EDITOR -d"
alias vn="$EDITOR -u NONE"
alias vc="$EDITOR ~/.vimrc"
alias vz="$EDITOR ~/.zshrc"
alias vs="$EDITOR slide*.vpm"
alias va="$EDITOR ~/.bash_aliases"
alias vh="$EDITOR ~/.zsh_history"
alias v3="$EDITOR ~/.config/i3/config"
alias vl="$EDITOR -c \"set background=light\""
alias vv="test \"$EDITOR\" = \"nvim\" && vim || nvim"

alias rz="source ~/.zshrc"
alias ra="source ~/.bash_aliases"
alias ri="i3-msg 'restart'"

alias sas="sudo apt-cache search"
alias sad="sudo apt-cache show"
alias sai="sudo apt-get install -y"
alias sar="sudo apt-get remove -y"
alias sau="sudo apt-get update && sudo apt-get upgrade -y && sac"
alias sac="sudo apt-get autoremove --purge -y && sudo apt-get clean -y && sudo apt-get autoclean -y"
alias sap="dpkg -l | grepx ^rc | grepx -v grub | awk '{print \$2}' | xargs -t sudo apt-get -y purge"

alias xpa='echo "\n" | sudo add-apt-repository'
alias xpr='echo "\n" | sudo add-apt-repository --remove'

alias c="phpx `which composer`"
alias c1="phpx `which composer_v1`"
alias ci="phpx `which composer` -vvv install"
alias cu="phpx `which composer` -vvv update"
alias ct="phpx `which composer` test"
alias cda="phpx `which composer` -vvv dump-autoload --optimize"
alias cii="phpx `which composer` -vvv install --ignore-platform-reqs"
alias cui="phpx `which composer` -vvv update --ignore-platform-reqs"
alias cip="phpx `which composer` -vvv install --no-dev"
alias cin="phpx `which composer` -vvv install --no-cache"
alias cipn="phpx `which composer` -vvv install --no-dev --no-cache"

alias pps="phpx bin/console"
alias ccs="sudo chmod 770 -Rf var                       && sudo chown $USER:www-data -Rf var                      && pps cache:clear"
alias ccm="sudo chmod 770 -Rf var                       && sudo chown $USER:www-data -Rf var                                                && gco var"

alias ppa="phpx artisan"
alias ccl="sudo chmod 770 -Rf storage bootstrap/cache   && sudo chown $USER:www-data -Rf storage bootstrap/cache  && ppa optimize:clear     && gco storage bootstrap"

alias ppv='ppa app-version:create --sha="$(git rev-parse HEAD)" --time="$(date -u +%Y%m%d%H%M%S)" --branch="$(git rev-parse --abbrev-ref HEAD)"'
alias ppy="export APPLICATION_ENV=dev && phpx yii"
alias ccy="sudo chmod 770 -Rf runtime web/assets        && sudo chown $USER:www-data -Rf runtime web/assets       && ppy cache/flush-all"

alias pex="sudo phpenmod xdebug"
alias pdx="sudo phpdismod xdebug"
alias prx='export XDEBUG_SESSION=1 && export XDEBUG_CONFIG="idekey=PHPSTORM" && phpx'
alias psw="sudo update-alternatives --config php"
alias prf="phprector -c /var/www/html/freddiegar/services/rector.php process"

alias vt="phpx vendor/bin/phpunit --stop-on-failure --no-coverage"
alias vT="phpx vendor/bin/phpunit --testdox -vvv"
alias vts="phpx vendor/bin/phpunit --stop-on-failure --no-coverage --testsuite"
alias vtS="phpx vendor/bin/phpunit --testdox -vvv --testsuite"
alias vtf="phpx vendor/bin/phpunit --stop-on-failure --no-coverage --filter"

alias vp="phpx vendor/bin/paratest --stop-on-failure --no-coverage"
alias vP="phpx vendor/bin/paratest --testdox -vvv"
alias vps="phpx vendor/bin/paratest --stop-on-failure --no-coverage --testsuite"
alias vpS="phpx vendor/bin/paratest --testdox -vvv --testsuite"
alias vpf="phpx vendor/bin/paratest --stop-on-failure --no-coverage --filter"

alias st="phpx bin/phpunit --stop-on-failure --no-coverage"
alias sT="phpx bin/phpunit --testdox -vvv"
alias sts="phpx bin/phpunit --stop-on-failure --no-coverage --testsuite"
alias stS="phpx bin/phpunit --testdox -vvv --testsuite"
alias stf="phpx bin/phpunit --stop-on-failure --no-coverage --filter"

alias vapor="phpx vendor/bin/vapor"
alias ducks="du -cks * | sort -rn | head"
alias fo="/opt/firefox/firefox --new-tab"

alias dexec="docker exec -it"
alias dlogs="docker logs --tail 50 -f"
alias dstart="docker start"
alias dstop="docker stop"
alias dstatus="docker ps --format \"{{.Names}}\""
alias dprune="docker system prune -a"
alias dstats="docker stats"
alias dclean="dcclean && diclean"
alias diclean="docker images | grep ' <none> ' | awk '{print \$3}' | xargs -r -I {} docker rmi {} && echo 'Images cleaned'"
alias dcclean="docker ps -a | grep ' Exited (1) ' | awk '{print \$1}' | xargs -r -I {} docker rm  -f {} && echo 'Containers cleaned'"

alias gs="git summary -q 2> /dev/null"
alias gf="onefetch --number-of-authors 5 --number-of-file-churns 5 --no-bots --no-merges --no-color-palette"
alias gv="gs | grep -v -E '/ro-|/_' | grep -E ' M?v'"
alias gV="gs | grep -v -E '/ro-|/_' | grep -E '\^$'"
alias gM="gs | grep -v -E '/ro-|/_' | grep -E 'M'"
alias gN="gs | grep -v -E '/ro-|/_' | grep -E '\?'"
alias gi="git init"
alias gt="git tag"
alias gst="git status"
alias gsts="git status --short"
alias gls="git ls-files"
# List modified traked files
alias glsm="git ls-files --modified"
# List deleted traked files
alias glsd="git ls-files --deleted"
# List ALL untraked files
alias glso="git ls-files --others"
# List ALL untraked files ignoring default exclusions: *.log
alias glsu="git ls-files --others --exclude-standard"
# List using root directory (usable inside NOT root directory)
alias glsf="git ls-files --full-name"
# List staged files
alias glss="git diff --name-only --cached | xargs -r -l echo"
# List assumed unchanged files
alias glsa="git ls-files -v | rg '^h ' | awk '{print \$2}'"

alias gd="git diff -w"
alias gda="git diff"
alias gdc="git diff -w --cached"
alias gdca="git diff --cached"
alias ga="git add"
alias gcm="git commit -S"
alias gcmn="git commit --no-verify -S"
alias gcmsg="git commit -S -m"
alias gcmsgn="git commit --no-verify -S -m"
alias gcmsga="git commit --amend -S -m"
alias gcmsgan="git commit --no-verify --amend -S -m"
alias gcmsgo="git commit --no-edit -C ORIG_HEAD"
alias gl="git pull"
alias glo="git pull origin"
alias gm="git merge"
alias gmu="git merge upstream/master"
alias gma="git merge --abort"
alias gp="git push"
alias gpo="git push origin"
# Whoops git pull revert rescue!
alias gpw="git reset --keep HEAD@{1}"
alias gpa="git push --all"
alias gb="git branch"
alias gbc="git branch --merged | grep -i -v -w -E 'master|main|develop' | xargs -r git branch -d"
alias gbn="git checkout master && git branch -M master && git push -u origin master"
alias gbb="git rev-parse --abbrev-ref HEAD | yy"
alias ggc="git gc --prune=now"
alias gck="git fsck --full --progress"
alias gfx="ggc && gck"
alias gfa="git fetch --all --prune"
alias gfu="git fetch upstream"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gcpn="git cherry-pick --no-commit"
alias gcob="git checkout -b"
alias gcot="git checkout version"
alias gsh="git stash"
alias gshp="git stash -p"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gsb="git stash branch"
alias gss="git stash show"
alias grh="git reset HEAD"
alias grH="git reset HEAD~"

# WARNING!: Overwrite local history with remote history
#   > Use ONLY when remote branch diverge of local branch
# @thanks https://stackoverflow.com/a/9589927/15601185
alias gfr="git reset --hard HEAD && git fetch --all && git reset --hard FETCH_HEAD && git clean -df"

alias gff="git flow init -d"
alias gffs="git flow feature start"
alias gfff="git flow feature finish"
alias gfbs="git flow bugfix start"
alias gfbf="git flow bugfix finish"
alias gfhs="git flow hotfix start"
alias gfhf="git flow hotfix finish"
alias gfrs="git flow release start"
alias gfrf="git flow release finish"

alias gr="git rebase"
alias gri="git rebase --interactive"
alias grc="git rebase --continue"
alias gra="git rebase --abort"

alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glop="glog -p"
alias glol="git show --name-only"
alias glof="git log --decorate=full --pretty=full --graph -b --stat"
alias glos="git log --show-signature"
alias gconf="git config --list"

# osc duckduck.com:443
alias osc="openssl s_client -brief -connect"
# osd duckduck.com:443.pem
alias osd="openssl x509 -noout -text -in"
# osx duckduck.com:443.pem
alias osx="openssl x509 -noout -dates -in"
# Check expirations in seconds 60*60*24*30 -> 2592000 (1 month)
# osv duckduck.com:443.pem
alias osv="openssl x509 -noout -checkend 2592000 -in"

alias cdh="cd /var/www/html"
alias cdt="cd /var/www/html/ataringenieria"
alias cde="cd /var/www/html/evertec"
alias cdx="cd /var/www/html/flexphp"
alias cdf="cd /var/www/html/freddiegar"

alias vdt="cdp /var/www/html/ataringenieria"
alias vde="cdp /var/www/html/evertec"
alias vdx="cdp /var/www/html/flexphp"
alias vdf="cdp /var/www/html/freddiegar"

alias cdd="cd /home/$USER/Downloads"

alias wr="convert -resize `xdpyinfo | awk '/dimensions/ {print $2}'`"
alias yy="xclip -selection clipboard"
alias pp="xclip -selection clipboard -o"

alias ff="command ls -L1 | while read file; do ffplay -autoexit -nostats -nodisp -vn -sn -hide_banner -- \$file; done"
alias fa="find . -type f -print | shuf | while read file; do ffplay -autoexit -nostats -nodisp -vn -sn -hide_banner -- \$file; done"
alias fj="pkill ffplay"
alias fn="ps -fea | g ffplay | g -F hide_banner | sed 's#^.*-- ##g'"
# fd <url>
alias fd="cd /home/$USER/Music && python3 /usr/local/bin/youtube-dl --ignore-errors --yes-playlist --yes-playlist --extract-audio -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"
# fm 09 <url>
alias fm="fd --playlist-items"
alias fu="python3 /usr/local/bin/youtube-dl -U"

# Last command BUT as sudo, need simple quotes!
# @see https://unix.stackexchange.com/a/158480
# alias pls='sudo $(fc -ln -1)'

# Expand alias after sudo
# @see https://stackoverflow.com/a/37210013
# alias sudo="sudo "
