#!/usr/bin/env bash

# Changes system time temporarily
# Usage datex [<date-as-YYYY-MM-DD>]
#   datex 2020-12-31    -> Set current time to 2020-12-31
#   datex               -> Set time to real current time

timedatectl status

if [ "$1" == "" ] ; then
    timedatectl set-ntp yes

    sleep 1
else
    timedatectl set-ntp no

    timedatectl set-time $1
fi

echo "============================ Now ============================"

timedatectl status | grepx "Local|Time|System"
