#!/usr/bin/env bash
set -o nounset

if [ -f composer.json ]; then
    `cat composer.json | grepx -F '"php":' | head -1 | sed -r "s#([^0-9]+)# #g" | awk '{print "/usr/bin/php"$1"."$2}'` "$@"

    exit 0
fi

`which php` "$@"
